services:
  app:
    build: .
    platform: linux/amd64
    ports:
      - "5050:5050"
    env_file:
      - ./.env
    volumes:
      - ~/.aws:/root/.aws
      - ./firebase-key.json:/app/firebase-key.json:ro
    restart: unless-stopped
